car = 'subaru'
print("Is car == 'subaru'? I predict True.")
print(car == 'subaru')
print("\nIs car == 'audi'? I predict False.")
print(car == 'audi')
car = 'toyota'
print("\nIs car == 'subaru'? I predict False.")
print(car == 'subaru')
print("\nIs car == 'honda'? I predict False.")
print(car == 'honda')
car = 'chevrolet'
print("\nIs car == 'subaru'? I predict True.")
print(car == 'chevrolet')
print("\nIs car == 'honda'? I predict False.")
print(car == 'fiat')
print("\nIs car == 'subaru'? I predict False.")
print(car == 'bmw')
car = 'dodge'
print("\nIs car == 'honda'? I predict True.")
print(car == 'dodge')
print("\nIs car == 'subaru'? I predict False.")
print(car == 'toyota')
print("\nIs car == 'honda'? I predict False.")
print(car == 'honda')
print("\nIs car == 'subaru'? I predict False.")
print(car == 'chevrolet')
print("\nIs car == 'honda'? I predict False.")
print(car == 'renault')
